# include/constants.py
import numpy as np

RENDER_DPI = 220

# SIFT
SIFT_RATIO = 0.76
SIFT_MIN_MATCHES = 6
SIFT_MIN_INLIERS = 5

# ORB
ORB_RATIO = 0.80
ORB_MIN_MATCHES = 8
ORB_MIN_INLIERS = 5

# Template
TEMPLATE_MIN_SCORE = 0.68
TEMPLATE_STRONG_SCORE = 0.80

# Edge
EDGE_MIN_SCORE = 0.58
EDGE_STRONG_SCORE = 0.72

# Detection limits
MAX_DETECTIONS_PER_METHOD = 40
MAX_FINAL_DETECTIONS = 50

# Merge
IOU_MERGE_THRESHOLD = 0.25
OVERLAP_SMALLER_THRESHOLD = 0.55
FINAL_DUPLICATE_IOU = 0.40

MIN_DETECTION_SIZE = 8

REMOVE_PADDING_PX = 3
INPAINT_RADIUS = 5

TEMPLATE_SCALES = np.linspace(0.30, 2.50, 23)

MIN_QUAD_AREA_RATIO = 0.00005
MAX_QUAD_AREA_RATIO = 0.95
MIN_QUAD_EDGE = 3.0
MAX_ASPECT_RATIO = 30.0

INPAINT_MIN_EDGE_SIMILARITY = 0.18
SEAMLESS_CLONE_ENABLED = True

OUTPUT_SUFFIX = "_edited"
CREATE_DEBUG_IMAGES = True

# Removal modes
MODE_INPAINT = "inpaint"
MODE_REDACT = "redact"
MODE_AUTO = "auto"